package alex;

public class ClaseLexica {
  public static final int EOF = 0;
  public static final int ENT = 2;
  public static final int REAL = 3;
  public static final int CHAR = 4;
  public static final int STR = 5;
  public static final int BOOL = 6;
  public static final int ÑINT = 7;
  public static final int ÑOUBLE = 8;
  public static final int ÑHAR = 9;
  public static final int ÑTRING = 10;
  public static final int ÑOOLEAN = 11;
  public static final int ÑIF = 12;
  public static final int ÑELSIF = 13;
  public static final int ÑELSE = 14;
  public static final int ÑOR = 15;
  public static final int ÑHILE = 16;
  public static final int ÑO = 17;
  public static final int ÑUN = 18;
  public static final int ÑOID = 19;
  public static final int ÑETURN = 20;
  public static final int ÑUE = 21;
  public static final int ÑALSE = 22;
  public static final int MAS = 23;
  public static final int MENOS = 24;
  public static final int POR = 25;
  public static final int DIV = 26;
  public static final int MEN = 27;
  public static final int MAY = 28;
  public static final int MENI = 29;
  public static final int MAYI = 30;
  public static final int ID = 31;
  public static final int PAP = 32;
  public static final int PCIERRE = 33;
  public static final int TAP = 34;
  public static final int TCIERRE = 35;
  public static final int IGUAL = 36;
  public static final int IAP = 37;
  public static final int ICIERRE = 38;
  public static final int BBAJA = 39;
  public static final int CONST = 40;
  public static final int ARBA = 41;
  public static final int COMA = 42;
}
