package asint;

public class ClaseLexica {
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ENT = 2;
  public static final int REAL = 3;
  public static final int CHAR = 4;
  public static final int STR = 5;
  public static final int BOOL = 6;
  public static final int ÑINT = 7;
  public static final int ÑOUBLE = 8;
  public static final int ÑHAR = 9;
  public static final int ÑTRING = 10;
  public static final int ÑOOLEAN = 11;
  public static final int ÑIF = 12;
  public static final int ÑELSIF = 13;
  public static final int ÑELSE = 14;
  public static final int ÑOR = 15;
  public static final int ÑHILE = 16;
  public static final int ÑO = 17;
  public static final int ÑUN = 18;
  public static final int ÑOID = 19;
  public static final int ÑETURN = 20;
  public static final int MAS = 21;
  public static final int MENOS = 22;
  public static final int POR = 23;
  public static final int DIV = 24;
  public static final int MEN = 25;
  public static final int MAY = 26;
  public static final int MENI = 27;
  public static final int MAYI = 28;
  public static final int IDEN = 29;
  public static final int PAP = 30;
  public static final int PCIERRE = 31;
  public static final int TAM = 32;
  public static final int IGUAL = 33;
  public static final int IAP = 34;
  public static final int ICIERRE = 35;
  public static final int LLAP = 36;
  public static final int LLCIERRE = 37;
  public static final int PC = 38;
  public static final int COMILLAS = 39;
  public static final int BBAJA = 40;
  public static final int CONST = 41;
  public static final int ARBA = 42;
  public static final int COMA = 43;
}
